---
- name: create nginx group
  group:
    name: nginx

- name: create “{{ deploy_user }}” user
  user:
    groups: nginx,wheel
    home: /home/{{ deploy_user }}
    name: "{{ deploy_user }}"
    password: "{{ deploy_pass }}"
    update_password: on_create

- name: add key to deploy user’s authorized_keys
  authorized_key:
    key: "{{ lookup('file', keyfile) }}"
    user: "{{ deploy_user }}"
